// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxWnj0PtqXId5LiyRXHNqB3BK7u3JVGdA',
    appId: '1:690006787908:web:e6fdff3a5d02f5b7c57911',
    messagingSenderId: '690006787908',
    projectId: 'todoo-790f8',
    authDomain: 'todoo-790f8.firebaseapp.com',
    storageBucket: 'todoo-790f8.appspot.com',
    measurementId: 'G-R7N08JW9EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAayYnTiy9TcJgIFAkKh2-Obyt6ZpSLoxQ',
    appId: '1:690006787908:android:378b72a56e0b8c8dc57911',
    messagingSenderId: '690006787908',
    projectId: 'todoo-790f8',
    storageBucket: 'todoo-790f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH8SAp6IGplYfzKDyLw7HyTZTKp3TIF8w',
    appId: '1:690006787908:ios:4e1387c4e94aee5dc57911',
    messagingSenderId: '690006787908',
    projectId: 'todoo-790f8',
    storageBucket: 'todoo-790f8.appspot.com',
    iosBundleId: 'com.example.todo',
  );

}